### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by gjmwolmarans** [typings/discussions#10]
Hey all, I'd like to volunteer to help move this project forward.
Please advise on where help is most needed.

**Comment by blakeembrey** [comment]
Hey @gjmwolmarans! What are you most interested in helping with? There's a few categories:
- Features
  - Things that are decoupled and pretty well defined
  - E.g. https://github.com/typings/typings/issues/27
- Typings
  - Improving the diversity of type definitions in the registry (https://github.com/typings/registry)
  - E.g. https://github.com/typings/typings/issues/125
- Documentation
  - If there's something that's poorly explained, we could use a simple explanation to point people to
  - I can think of a couple of things I've been meaning to write but features/bugs always pop up first, like "What's the different between normal and `--ambient`?" and https://github.com/typings/typings/issues/274
- Answers
  - Answering issues in https://github.com/typings/typings and StackOverflow would be amazing (I haven't even checked StackOverflow myself)

Does this help?

**Comment by gjmwolmarans** [comment]
@blakeembrey, I'm willing to help in any way I can, but I'd like to contribute in a way that is in line with the project initiators' priorities. To rephrase: what "grunt" work will add the most value?

I'd really like to see is a VS Code extension that automatically detects missing typings and offers installation as a quick fix.

**Comment by blakeembrey** [comment]
> I'd like to contribute in a way that is in line with the project initiators' priorities

The things listed above are the priorities. Basically need to provide value wherever it's most immediate.

> I'd really like to see is a VS Code extension that automatically detects missing typings and offers installation as a quick fix.

This would be freaking amazing! I know @unional is working with VSCode in https://github.com/typings/vscode and this is definitely how I see it working too. 

Reference: https://github.com/typings/typings/issues/306#issuecomment-195835855

**Comment by unional** [comment]
@gjmwolmarans You are definitely welcome to work on the vscode extension! :smile:
