### ISSUE TITLE
Silly question, but I'm unable to find a way to view the typings registry

### ISSUE THREAD

**Issue by blaster151** [typings/discussions#12]
How do I actually view it?

**Comment by demurgos** [comment]
I know that there is a website under development and a simple API is available but the easiest way to browse all the typings is to simply explore the [registry's repository](https://github.com/typings/registry).

**Comment by blakeembrey** [comment]
@blaster151 What are you actually trying to do? As @Demurgos mentions, the registry is available at https://github.com/typings/registry and the API source code is public at https://github.com/typings/api. The deployed API is available at http://api.typings.org/ and is used every day by Typings.

Feel free to continue asking more questions if that hasn't answered it.
