### ISSUE TITLE
Are multiple versions for a given typing planned?

### ISSUE THREAD

**Issue by gCardinal** [typings/discussions#17]
I will clarify my question: Looking through the registry, I could not find typings that did not point to a single version of a given library's typings. Let's take [redux-thunk](https://github.com/typings/registry/blob/master/npm/redux-thunk.json) as an example, right now it's pointing to typings for version 1.0.4. When/if redux-thunk releases a version 1.0.5 or 2.0.0, is there plan to simply add this version and keep the old version so it becomes possible to download either versions of the typings, depending on which one is used in a given project?

I feel like that is the plan, but I would like to confirm since that's something that did stop me from using TypeScript in the past, the way DefinitelyTyped handled versioning of typpings and how convoluted that repository became.

**Comment by demurgos** [comment]
Even if its not very used for the moment, `typings` was built with multiple versions in mind. [The Node.js typings](https://github.com/typings/registry/blob/master/env/node.json) actually use this feature.

> When/if redux-thunk releases a version 1.0.5 or 2.0.0, is there plan to simply add this version and keep the old version so it becomes possible to download either versions of the typings, depending on which one is used in a given project?

Yes that's the plan :wink:.

**Comment by gCardinal** [comment]
Awesome. I have a follow-up question if I may. Are typings required to come from the same repository or could 1.0.0 and 2.0.0 be from different repository? 

I'm sure it's a weird question, but I'm just trying to evaluate the long term viability of switching to TypeScript.

**Comment by demurgos** [comment]
As you can see with the Node example, the versions are handled independently: each one has a full path to the definitions location. Again, the project is young so its hard to find real-life examples, but if you want to, you can use different repositories for different versions of your typings.

**Comment by gCardinal** [comment]
Yes, I saw. I thought maybe you already had guidelines setup for this kind of thing.

Thank you for your answers!

**Comment by blakeembrey** [comment]
Thanks @demurgos 😄 Great answers! Yes, you can have multiple repos/locations. Yes, old pointers are kept always on the registry API - but deleted references stop showing up in search. So even when it's deleted on the registry, the pointer stays alive for people depending on it.
