### ISSUE TITLE
What is "env" source? 

### ISSUE THREAD

**Issue by s-KaiNet** [typings/discussions#18]
Can you please explain this a bit more?  
For example I run `typings search node` and results show me that node available as "env" source.  
What does that mean? And how to install node from "env" source?  
I've tried `typings install env:node` (ha-ha) without success.

**Comment by blakeembrey** [comment]
See https://github.com/typings/typings#quick-start and https://github.com/typings/registry#structure. I'll be adding the sources from the registry into the Typings README ASAP.

**Comment by s-KaiNet** [comment]
wow, thanks for super fact response.  
I'm confused about the syntax, because this page - [https://github.com/typings/typings/blob/master/docs/commands.md](https://github.com/typings/typings/blob/master/docs/commands.md) says that you need to use `:` syntax instead of `!`, i.e. `npm:<package>` etc..

**Comment by blakeembrey** [comment]
That's a separate feature. One uses the registry (source), the other is a scheme. You should see in the command that both syntaxes are documented separately, and both are valid. E.g. `foo!bar` finds "bar" of "foo" in the registry, while `foo:bar` resolves "bar" using "foo" resolution. In concrete terms, `npm!debug` finds `debug` on the registry and installs it. `npm:debug` uses node module resolution to find `debug` locally.

**Comment by s-KaiNet** [comment]
now it's clear. Thanks again
