### ISSUE TITLE
Adding a new repository under the typed-typings organization

### ISSUE THREAD

**Issue by cantide5ga** [typings/discussions#22]
I've been working locally with slightly tweaked DT definition files for React and Flux to un-globalize them and would like to add them to the registry.  Good information I'm following in the registry README, but didn't quite catch the process to add the typings under the typed-typings namespace.

**Comment by blakeembrey** [comment]
@cantide5ga You can put them under you're own repo. The `typed-typings` is mostly a few people I've added and myself who've added repos there (or moved them at a later time). If you wanted, I can also add you as a member so you can create repos there.

**Comment by cantide5ga** [comment]
Ok, I got a PR ready to go for this along with a couple others.  And yeah, go ahead and add me, that would be great - especially if that is the preference.  I'll move them over to the organization as soon as I can. 

A couple more questions:
- is there a review process for the typings themselves?  I want to make sure I'm following best practices.
- is there any intuitive way you guys determine the minimum semver the typings are valid for?  I'm going with the current version of all the libs to be safe, but they could very well work with previous versions as well.

**Comment by unional** [comment]
> is there a review process for the typings themselves? I want to make sure I'm following best practices.

Good idea. I should write up something (and have Johnny and Blake review it) 😄 

> is there any intuitive way you guys determine the minimum semver the typings are valid for? I'm going with the current version of all the libs to be safe, but they could very well work with previous versions as well.

Currently `generator-typings` beta will get the current version of the package automatically. It would be an interesting idea to back test against previous versions. Seems doable with npm packages.

**Comment by unional** [comment]
@cantide5ga just added you to typed-typings. 👍
