### ISSUE TITLE
Many modules are not found after updating to 1.0.4

### ISSUE THREAD

**Issue by Zzzen** [typings/discussions#23]
> E:\YAP>typings install github-electron --save
> typings ERR! message Unable to find "github-electron" ("npm") in the registry. Did you want to try searching another source? Also, if you want contribute these typings, please help us: https://github.com/typings/registry
> typings ERR! caused by https://api.typings.org/entries/npm/github-electron/versions/latest responded with 404, expected it to equal 200
> 
> typings ERR! cwd E:\YAP
> typings ERR! system Windows_NT 10.0.10586
> typings ERR! command "E:\Nodejs\node.exe" "C:\Users\Administrator\AppData\Roaming\npm\node_modules\typings\dist\bin.js" "install" "github-electron" "--save"
> typings ERR! node -v v5.10.1
> typings ERR! typings -v 1.0.4

**Comment by blakeembrey** [comment]
Please check the README and existing issues. You've updated to 1.0 and the instructions are in the README of https://github.com/typings/typings#updating-from-0x-to-10.
