### ISSUE TITLE
Example Typings : Multi-Module NPM with RequireJS

### ISSUE THREAD

**Issue by phreed** [typings/discussions#25]
In the examples...
https://github.com/typings/typings/blob/master/docs/examples.md
...there does not seem to be one for RequireJS.
Is there an example package that does?
There is an example for CommonJs/NodeJs (3).

Incidentally, this is the substance of what I was trying to convey with #19

**Comment by blakeembrey** [comment]
@phreed Writing Typings for RequireJS should look identical to CommonJS - it's only documenting the keys/values you export and does not care about the underlying module system. That said, I haven't done it myself and if it doesn't work hopefully someone else can give more advice.

What issues have you run into?

**Comment by phreed** [comment]
There are two coordinated issues here.
One is related to 'typings' the other to 'typescript'.
The focus is the 'import' statement and how it generates the AMD for the xyz.js and parses the xyz.d.ts.

Suppose we have an existing npm module containing a
[module as a function](http://requirejs.org/docs/api.html#funcmodule).
In particular we have an xyz.d.ts defining multiple modules.
We wish to import these modules individually.

``` typescript
import PS from 'xyz/abc');
class Ps extends PS {
  constructor() { super(); }
  s(): string { return '0.1.0'; }
}
```

Using the 'require.path' setting, the 'xyz/abc' can be configured to obtain the proper xyz.js file.
What is the proper way to construct the 'xyz.d.ts' content to select the proper module definition?
I am pretty sure the following is flawed but I hope it is sufficiently notional.

``` typescript
declare namespace nJS {
  export interface ABC { s(): string; }
  export interface DEF { t(): number; }
}
declare module "abc" {
   export default class PS implements nJS.ABC { constructor();  s(): string; }
}
declare module "def" {
   export default class PT implements nJS.DEF { constructor(); t(): number; }
}
```

note:
It appears that typings combines the *.d.ts files from the repository into a single 'index.d.ts' file and defines modules in that file. How is this composition performed?

**Comment by phreed** [comment]
The following links have proven useful.
[An example of modules being defined](https://github.com/typed-typings/env-node/blob/master/0.12/node.d.ts)
In particular the 
[discussion on "Default Exports" and "Working with Other JavaScript Libraries"](https://www.typescriptlang.org/docs/handbook/modules.html).

**Comment by phreed** [comment]
It is now working for me.
