### ISSUE TITLE
Don't understand globals, dt~css must be installed as global but shouldn't according to FAQ

### ISSUE THREAD

**Issue by andersea** [typings/discussions#29]
The faq says -

> Global dependencies are type definitions that are global or otherwise provide information about the environment. Some examples of "environment" dependencies are Node.js, Browserify, window and even Array.prototype.map. These are globals that exist at runtime, you do not "require" them.

I am using the css module from npm and try to install typings using `typings install dt~css`, the logic being that according to the faq, since i need to require (or import) the module in order to use it, then it is not a global.

However i get the error.

`Attempted to compile "css" as an external module, but it looks like a global module. You'll need to enable the global option to continue.`

This doesn't make any sense to me.

**Comment by blakeembrey** [comment]
You tried to install something from DefinitelyTyped. Pretty much everything in DefinitelyTyped is written in global definition format. This is a format for TypeScript definitions. DefinitelyTyped does not follow the Typings convention. You're welcome to make a PR to improve documentation.
