### ISSUE TITLE
Move typings

### ISSUE THREAD

**Issue by blakeembrey** [typings/discussions#7]
Make a "typed typings" organisation to hold all the typings being created "officially".

**Comment by blakeembrey** [comment]
https://github.com/typed-typings - still considering better naming suggestions. Some of the better ones: `gettypings`, `typings-central`.

**Comment by SomaticIT** [comment]
Hi @blakeembrey,

I currently maintain an organization called `typed-contrib` which already host some TypeScript definitions.

Maybe should I merge it with `typed-typings` organization ? What do you think ?

I can also free the name `typed-contrib` if you want it to be the name for the "official" `typings` organization (grunt-like).

**Comment by blakeembrey** [comment]
You're absolutely welcome to do so. I can make you a member now. 

Edit: Oh, it appears I already did 😄 You're welcome to merge whatever you want into there, as long as typings are following the existing structure it's great to have them all under one roof.
